import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import groq from "groq";
import sanityClient from "utils/sanityClient";

const query = groq`

*[_type == 'book']{
  title,
  slug,
  
}

`;

export async function getStaticProps() {
  const books = await sanityClient.fetch(query);
  return {
    props: { books },
  };
}

export default function Home({ books }) {
  // console.log(books);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>bOOKFD</h1>
        <div>
          {books.map((book) => (
            <h3>{book.title}</h3>
          ))}
        </div>
      </div>
    </div>
  );
}
