import Head from "next/head";
import Image from "next/image";

import groq from "groq";
import sanityClient from "utils/sanityClient";
import Meta from "@components/Meta";
import book from "bookstore/schemas/book";

const query = groq`
*[_type == 'book']  | order(title asc){
  title,
  "slug": slug.current,
  synopsis,
  series -> {title},
  author -> {name},
  coverImage{
     asset ->{url}
   }

}
`;

export async function getStaticProps() {
  const books = await sanityClient.fetch(query);
  return {
    props: { books },
  };
}

export default function Home({ books }) {
  // console.log(books);
  return (
    <>
      <Meta pageMeta={{ title: "The Little Nook" }} />
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className="flex flex-col">
        <h1 className="text-3xl mb-4 text-center">The Little Nook</h1>
        <p className="text-md mb-8 text-center">
          Your little corner for preloved books
        </p>
        {/* {books && books.map((book) => <h3>{book.title}</h3>)} */}
        <div className="grid grid-cols-3 gap-6">
          {books &&
            books.map((book) => (
              <article key={book.title} className="">
                <h2 className="font-semibold text-xl">{book.title}</h2>
                <p className="mb-2">{book.author.name}</p>
                <p className="line-clamp-3 mb-2">{book.synopsis}</p>
                <small>{book?.series?.title}</small>
              </article>
            ))}
        </div>
      </div>
    </>
  );
}
